version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "8883:8883"
    volumes:
      - "C:/Users/moham/IoTProject/config/mosquitto.conf:/mosquitto/config/mosquitto.conf"
      - "C:/Users/moham/IoTProject/certs:/mosquitto/config/certs"
